In [1]:
import cv2
import numpy as np
cpt=cv2.VideoCapture(0)
object_detect=cv2.createBackgroundSubtractorMOG2()
train_images=[]
train_labels=[]
while True:
    ret,frame=cpt.read()
    frame=cv2.resize(frame,(256,256))
    mask=object_detect.apply(frame)
    # counters,_=cv2.findContours(mask,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
    # print(counters)
    # for cnt in counters:
    # area=cv2.contourArea(cnt)
        # print(area)
        # if area>200:
    x,y,w,h=0,90,256,160
    frame=cv2.rectangle(frame,(x,y),(x+w,y+h),(0,255,0),3)
    cv2.imshow("win",frame)
    cv2.imshow("mask",mask)
    frame= frame.astype('float32') / 255.0 
    train_images.append(frame)
    train_labels.append("left")
    if cv2.waitKey(1)==ord('p'):
        break

cpt.release()
cv2.destroyAllWindows()

In [2]:
import cv2
import numpy as np
import mediapipe as mp
import uuid

In [3]:
mpdrawing=mp.solutions.drawing_utils
mphands=mp.solutions.hands

In [2]:
import cv2
import numpy as np
import mediapipe as mp
import uuid
mpdrawing=mp.solutions.drawing_utils
mphands=mp.solutions.hands
train_images=[]
train_labels=[]

cpt=cv2.VideoCapture(0)
with mphands.Hands(min_detection_confidence=0.8,min_tracking_confidence=0.5) as hands:
    while True:
        ret,frame=cpt.read()
        img=cv2.cvtColor(frame,cv2.COLOR_BGR2RGB)
        img.flags.writeable=False
        res=hands.process(img)
        img.flags.writeable=True
        img=cv2.cvtColor(img,cv2.COLOR_RGB2BGR)
        if res.multi_hand_landmarks:
            for num,hand in enumerate(res.multi_hand_landmarks):
                mpdrawing.draw_landmarks(img,hand,mphands.HAND_CONNECTIONS)

        img= img.astype('float32') / 255.0 
        img=cv2.resize(img,(256,256))
        cv2.imshow("win",img)
        train_images.append(img)
        train_labels.append("left")

        if cv2.waitKey(1)==ord('p'):
            break

    cpt.release()
    cv2.destroyAllWindows()

In [3]:
len(train_labels)

1591

In [4]:
import cv2
import numpy as np
import mediapipe as mp
import uuid
mpdrawing=mp.solutions.drawing_utils
mphands=mp.solutions.hands


cpt=cv2.VideoCapture(0)
with mphands.Hands(min_detection_confidence=0.8,min_tracking_confidence=0.5) as hands:
    while True:
        ret,frame=cpt.read()
        img=cv2.cvtColor(frame,cv2.COLOR_BGR2RGB)
        img.flags.writeable=False
        res=hands.process(img)
        img.flags.writeable=True
        img=cv2.cvtColor(img,cv2.COLOR_RGB2BGR)
        if res.multi_hand_landmarks:
            for num,hand in enumerate(res.multi_hand_landmarks):
                mpdrawing.draw_landmarks(img,hand,mphands.HAND_CONNECTIONS)

        img= img.astype('float32') / 255.0 
        img=cv2.resize(img,(256,256))
        cv2.imshow("win",img)
        train_images.append(img)
        train_labels.append("right")

        if cv2.waitKey(1)==ord('p'):
            break

    cpt.release()
    cv2.destroyAllWindows()

In [5]:
len(train_labels)

3617

In [6]:
import cv2
import numpy as np
import mediapipe as mp
import uuid
mpdrawing=mp.solutions.drawing_utils
mphands=mp.solutions.hands


cpt=cv2.VideoCapture(0)
with mphands.Hands(min_detection_confidence=0.8,min_tracking_confidence=0.5) as hands:
    while True:
        ret,frame=cpt.read()
        img=cv2.cvtColor(frame,cv2.COLOR_BGR2RGB)
        img.flags.writeable=False
        res=hands.process(img)
        img.flags.writeable=True
        img=cv2.cvtColor(img,cv2.COLOR_RGB2BGR)
        if res.multi_hand_landmarks:
            for num,hand in enumerate(res.multi_hand_landmarks):
                mpdrawing.draw_landmarks(img,hand,mphands.HAND_CONNECTIONS)

        img= img.astype('float32') / 255.0 
        img=cv2.resize(img,(256,256))
        cv2.imshow("win",img)
        train_images.append(img)
        train_labels.append("up")

        if cv2.waitKey(1)==ord('p'):
            break

    cpt.release()
    cv2.destroyAllWindows()

In [7]:
len(train_labels)

5141

In [8]:
import cv2
import numpy as np
import mediapipe as mp
import uuid
mpdrawing=mp.solutions.drawing_utils
mphands=mp.solutions.hands


cpt=cv2.VideoCapture(0)
with mphands.Hands(min_detection_confidence=0.8,min_tracking_confidence=0.5) as hands:
    while True:
        ret,frame=cpt.read()
        img=cv2.cvtColor(frame,cv2.COLOR_BGR2RGB)
        img.flags.writeable=False
        res=hands.process(img)
        img.flags.writeable=True
        img=cv2.cvtColor(img,cv2.COLOR_RGB2BGR)
        if res.multi_hand_landmarks:
            for num,hand in enumerate(res.multi_hand_landmarks):
                mpdrawing.draw_landmarks(img,hand,mphands.HAND_CONNECTIONS)

        img= img.astype('float32') / 255.0 
        img=cv2.resize(img,(256,256))
        cv2.imshow("win",img)
        train_images.append(img)
        train_labels.append("down")

        if cv2.waitKey(1)==ord('p'):
            break

    cpt.release()
    cv2.destroyAllWindows()

In [9]:
import cv2
import numpy as np
import mediapipe as mp
import uuid
mpdrawing=mp.solutions.drawing_utils
mphands=mp.solutions.hands


cpt=cv2.VideoCapture(0)
with mphands.Hands(min_detection_confidence=0.8,min_tracking_confidence=0.5) as hands:
    while True:
        ret,frame=cpt.read()
        img=cv2.cvtColor(frame,cv2.COLOR_BGR2RGB)
        img.flags.writeable=False
        res=hands.process(img)
        img.flags.writeable=True
        img=cv2.cvtColor(img,cv2.COLOR_RGB2BGR)
        if res.multi_hand_landmarks:
            for num,hand in enumerate(res.multi_hand_landmarks):
                mpdrawing.draw_landmarks(img,hand,mphands.HAND_CONNECTIONS)

        img= img.astype('float32') / 255.0 
        img=cv2.resize(img,(256,256))
        cv2.imshow("win",img)
        train_images.append(img)
        train_labels.append("fist")

        if cv2.waitKey(1)==ord('p'):
            break

    cpt.release()
    cv2.destroyAllWindows()

In [10]:
train_images=np.array(train_images)
train_labels=np.array(train_labels)

In [11]:
import pandas as pd
train_labels=pd.get_dummies(train_labels)
train_labels

down   fist   left  right     up
0     False  False   True  False  False
1     False  False   True  False  False
2     False  False   True  False  False
3     False  False   True  False  False
4     False  False   True  False  False
...     ...    ...    ...    ...    ...
8455  False   True  False  False  False
8456  False   True  False  False  False
8457  False   True  False  False  False
8458  False   True  False  False  False
8459  False   True  False  False  False

[8460 rows x 5 columns]

In [12]:
train_labels=np.array(train_labels)
train_labels

array([[False, False,  True, False, False],
       [False, False,  True, False, False],
       [False, False,  True, False, False],
       ...,
       [False,  True, False, False, False],
       [False,  True, False, False, False],
       [False,  True, False, False, False]])

In [1]:
np.save("train_images2.npy",train_images)
np.save("train_labels2.npy",train_labels)


KeyboardInterrupt



In [1]:
import numpy as np
train_images=np.load("train_images2.npy")
train_labels=np.load("train_labels2.npy")

In [2]:
train_labels

array([[False, False,  True, False, False],
       [False, False,  True, False, False],
       [False, False,  True, False, False],
       ...,
       [False,  True, False, False, False],
       [False,  True, False, False, False],
       [False,  True, False, False, False]])

In [3]:
train_images.shape

(8460, 256, 256, 3)

In [4]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense,Flatten,Conv2D,MaxPooling2D,BatchNormalization,Dropout

In [5]:
model = Sequential()

model.add(Conv2D(8,kernel_size=(3,3),padding='valid',activation='relu',input_shape=(256,256,3)))

model.add(MaxPooling2D(pool_size=(2,2),strides=2,padding='valid'))

model.add(Conv2D(16,kernel_size=(3,3),padding='valid',activation='relu'))

model.add(MaxPooling2D(pool_size=(2,2),strides=2,padding='valid'))

model.add(Conv2D(32,kernel_size=(3,3),padding='valid',activation='relu'))

model.add(MaxPooling2D(pool_size=(2,2),strides=2,padding='valid'))

model.add(Flatten())
model.add(Dense(32,activation='relu'))

model.add(Dense(8,activation='relu'))

model.add(Dense(5,activation='softmax'))

In [6]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 254, 254, 8)       224       
                                                                 
 max_pooling2d (MaxPooling2  (None, 127, 127, 8)       0         
 D)                                                              
                                                                 
 conv2d_1 (Conv2D)           (None, 125, 125, 16)      1168      
                                                                 
 max_pooling2d_1 (MaxPoolin  (None, 62, 62, 16)        0         
 g2D)                                                            
                                                                 
 conv2d_2 (Conv2D)           (None, 60, 60, 32)        4640      
                                                                 
 max_pooling2d_2 (MaxPoolin  (None, 30, 30, 32)        0

In [7]:
model.compile(
    optimizer="adam",
    loss='categorical_crossentropy',
    metrics=['accuracy']
  )

In [12]:
from tensorflow.keras.callbacks import EarlyStopping

# Define the EarlyStopping callback
callback = EarlyStopping(
    monitor='accuracy', # or 'val_accuracy' if you want to monitor validation accuracy
    mode='auto', # 'auto' determines whether the monitored quantity should be maximized or minimized automatically
    patience=0, # How many epochs to wait after the condition is met. 0 means the training will stop immediately after reaching the threshold.
    verbose=1, # To print a message when the callback triggers.
    baseline=0.95 # Threshold for stopping, but note: 'threshold' is not a valid argument for EarlyStopping
)


In [13]:
history = model.fit(train_images,train_labels,batch_size=75,epochs=7,callbacks=callback)

Epoch 1/7
 16/113 [===>..........................] - ETA: 2:34 - loss: 8.6791e-05 - accuracy: 1.0000

: 

In [9]:
model.save("multi class model 5")

INFO:tensorflow:Assets written to: multi class model 5\assets


INFO:tensorflow:Assets written to: multi class model 5\assets


In [14]:

from tensorflow.keras.models import load_model
model=load_model("multi class model 3")

In [10]:
import cv2
import numpy as np
import mediapipe as mp
import uuid
mpdrawing=mp.solutions.drawing_utils
mphands=mp.solutions.hands


cpt=cv2.VideoCapture(0)
with mphands.Hands(min_detection_confidence=0.8,min_tracking_confidence=0.5) as hands:
    while True:
        ret,frame=cpt.read()
        img=cv2.cvtColor(frame,cv2.COLOR_BGR2RGB)
        img.flags.writeable=False
        res=hands.process(img)
        img.flags.writeable=True
        img=cv2.cvtColor(img,cv2.COLOR_RGB2BGR)
        if res.multi_hand_landmarks:
            for num,hand in enumerate(res.multi_hand_landmarks):
                mpdrawing.draw_landmarks(img,hand,mphands.HAND_CONNECTIONS)

        img= img.astype('float32') / 255.0 
        img=cv2.resize(img,(256,256))
        cv2.imshow("win",img)

         
        img = np.expand_dims(img, axis=0)
        res=model.predict(img)
        a=res.argmax()
        if a==0:
            print("down")
        elif a==1:
            print("fist")
        elif a==2:
            print("left")
        elif a==3:
            print("right")
        elif a==4:
            print("up")


        
        if cv2.waitKey(500)==ord('p'):
            break

    cpt.release()
    cv2.destroyAllWindows()

1/1 [==============================] - 0s 220ms/step
left
1/1 [==============================] - 0s 29ms/step
right
1/1 [==============================] - 0s 27ms/step
left
1/1 [==============================] - 0s 27ms/step
up
1/1 [==============================] - 0s 30ms/step
up
1/1 [==============================] - 0s 26ms/step
up
1/1 [==============================] - 0s 26ms/step
up
1/1 [==============================] - 0s 26ms/step
up
1/1 [==============================] - 0s 25ms/step
up
1/1 [==============================] - 0s 28ms/step
up
1/1 [==============================] - 0s 26ms/step
up
1/1 [==============================] - 0s 30ms/step
right
1/1 [==============================] - 0s 28ms/step
right
1/1 [==============================] - 0s 25ms/step
right
1/1 [==============================] - 0s 26ms/step
right
1/1 [==============================] - 0s 23ms/step
right
1/1 [==============================] - 0s 23ms/step
right
1/1 [==============================] - 

In [2]:
import numpy as np
train_images=np.load("train_images2.npy")
train_labels=np.load("train_labels2.npy")

In [7]:
frame=train_images[200]
frame

array([[[0.7194853 , 0.7386642 , 0.735723  ],
        [0.7121324 , 0.72898287, 0.71452206],
        [0.7151348 , 0.73125   , 0.70091915],
        ...,
        [0.83958334, 0.8523285 , 0.8265319 ],
        [0.8369486 , 0.85269606, 0.80759805],
        [0.8435662 , 0.85490197, 0.80784315]],

       [[0.71795344, 0.7375613 , 0.72781867],
        [0.71292895, 0.73645836, 0.7139706 ],
        [0.714951  , 0.73878676, 0.7110294 ],
        ...,
        [0.8276348 , 0.84227943, 0.8004902 ],
        [0.84344363, 0.86335784, 0.81832105],
        [0.8403799 , 0.8599878 , 0.814951  ]],

       [[0.71770835, 0.7405025 , 0.72634804],
        [0.71433824, 0.74595594, 0.7191789 ],
        [0.70980394, 0.74491423, 0.7139093 ],
        ...,
        [0.8433211 , 0.8629289 , 0.8197304 ],
        [0.8415441 , 0.8609681 , 0.81556374],
        [0.83523285, 0.8548407 , 0.8092525 ]],

       ...,

       [[0.539277  , 0.57322305, 0.58045346],
        [0.51299024, 0.5536152 , 0.55753684],
        [0.5188726 , 0

In [5]:
import cv2
cv2.imshow("win",train_images[1])

In [10]:
import cv2
import numpy as np

while True:
    frame=train_images[2300]
    cv2.imshow("win",frame)
    print(frame)
    if cv2.waitKey(000)==ord('p'):
        break

cpt.release()
cv2.destroyAllWindows()

[[[0.69442403 0.69963235 0.6921569 ]
  [0.6890931  0.70906866 0.70232844]
  [0.6776348  0.7056373  0.69460785]
  ...
  [0.8079657  0.83321077 0.8042892 ]
  [0.8009191  0.8245098  0.78584564]
  [0.79632354 0.814277   0.7732843 ]]

 [[0.689951   0.7035539  0.69031864]
  [0.6848039  0.7036152  0.68915445]
  [0.6840074  0.70392156 0.6922182 ]
  ...
  [0.8061274  0.8220588  0.78406864]
  [0.80422795 0.8201593  0.7821691 ]
  [0.79687506 0.81348044 0.77726716]]

 [[0.6892157  0.71513486 0.68529415]
  [0.68443626 0.7096201  0.6854167 ]
  [0.6765932  0.69803923 0.6793505 ]
  ...
  [0.8020221  0.7988358  0.7635417 ]
  [0.79834557 0.8020221  0.7721201 ]
  [0.8092525  0.8185662  0.79111516]]

 ...

 [[0.5022059  0.54534316 0.55006135]
  [0.5051471  0.54828435 0.5553922 ]
  [0.5071691  0.5447304  0.548652  ]
  ...
  [0.43180147 0.48946083 0.5382966 ]
  [0.19797795 0.25992647 0.36482844]
  [0.14515932 0.2297794  0.33639708]]

 [[0.5035539  0.5456495  0.54172796]
  [0.50643384 0.54172796 0.5390319 ]
